DROP TABLE IF EXISTS landmarks;
DROP TABLE IF EXISTS favorites;

CREATE TABLE landmarks (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
);

CREATE TABLE favorites (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
);